// Documents/dev/personal-budget-react/src/HomePage/HomePage.js
import React from 'react';

function HomePage() {
  return (
    <main className="center" id="main">

        <section className="page-area">

            <article>
                <h2>Stay on track</h2>
                <p>
                    Do you know where you are spending your money? If you really stop to track it down,
                    you would get surprised! Proper budget management depends on real data... and this
                    app will help you with that!
                </p>
            </article>

            <article>
                <h2>Alerts</h2>
                <p>
                    What if your clothing budget ended? You will get an alert. The goal is to never go over the budget.
                </p>
            </article>
    
            <article>
                <h2>Results</h2>
                <p>
                    People who stick to a financial plan, budgeting every expense, get out of debt faster!
                    Also, they live happier lives... since they spend without guilt or fear... 
                    because they know it is all good and accounted for.
                </p>
            </article>
    
            <article>
                <h2>Free</h2>
                <p>
                    This app is free!!! And you are the only one holding your data!
                </p>
            </article>
    
            <article>
                <h2>Charts</h2>
                <div className="chart-container">
                    <div className="chart-box">
                        <canvas id="myChart" width="400" height="400" aria-label="Budget distribution pie chart" role="img"></canvas>
                    </div>
                    <div className="chart-box">
                        <div id="d3Chart"></div>
                    </div>
                </div>
            </article>

        </section>

    </main>
  );
}

export default HomePage;

// Documents/dev/personal-budget-angular/personal-budget-angular/src/app/homepage/homepage.component.ts
import { Component, Inject, OnInit, PLATFORM_ID } from '@angular/core';
import { ArticleComponent } from '../article/article.component';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { Chart, ChartConfiguration, registerables } from 'chart.js';
import { isPlatformBrowser } from '@angular/common';

interface BudgetItem {
  title: string;
  budget: number;
}

@Component({
  selector: 'pb-homepage',
  standalone: true,
  imports: [ArticleComponent, HttpClientModule],
  templateUrl: './homepage.component.html',
  styleUrls: ['./homepage.component.scss']
})
export class HomepageComponent implements OnInit {
  public dataSource = {
    datasets: [
      {
        data: [] as number[],
        backgroundColor: [
          '#ffcd56',
          '#ff6384',
          '#36a2eb',
          '#fd6b19',
        ]
      }
    ],
    labels: [] as string[]
  };

  constructor(private http: HttpClient, @Inject(PLATFORM_ID) private platformId: object) {
    Chart.register(...registerables);
  }

  ngOnInit(): void {
    this.http.get<{ myBudget: BudgetItem[] }>('http://localhost:3000/budget')
      .subscribe({
        next: (res) => {
          res.myBudget.forEach((item, i) => {
            this.dataSource.datasets[0].data[i] = item.budget;
            this.dataSource.labels[i] = item.title;
          });

          if (isPlatformBrowser(this.platformId)) {
            this.createChart();
          }
        },
        error: (err) => {
          console.error('Error fetching budget:', err);
          alert('Failed to connect to the backend. Ensure the API is running.');
        }
      });
  }

  createChart() {
    if (isPlatformBrowser(this.platformId)) {
      const canvas = document.getElementById('myChart') as HTMLCanvasElement;
      if (canvas) {
        new Chart(canvas.getContext('2d')!, {
          type: 'pie',
          data: this.dataSource,
          options: {
            responsive: true,
            maintainAspectRatio: false
          }
        } as ChartConfiguration);
      } else {
        console.error('Canvas element not found');
      }
    }
  }
}

<main class="center" id="main">

    <div class="page-area">

        <pb-article>
          <h1>Stay on track</h1>
                <p>
                    Do you know where you are spending your money? If you really stop to track it down,
                    you would get surprised! Proper budget management depends on real data... and this
                    app will help you with that!
                </p>
        </pb-article>

        <pb-article>
            <h1>Alerts</h1>
            <p>
                What if your clothing budget ended? You will get an alert. The goal is to never go over the budget.
            </p>
        </pb-article>

        <pb-article>
            <h1>Results</h1>
            <p>
                People who stick to a financial plan, budgeting every expense, get out of debt faster!
                Also, they to live happier lives... since they expend without guilt or fear...
                because they know it is all good and accounted for.
            </p>
        </pb-article>

        <pb-article>
            <h1>Free</h1>
            <p>
                This app is free!!! And you are the only one holding your data!
            </p>
        </pb-article>

        <pb-article>
            <h1>Stay on track</h1>
            <p>
                Do you know where you are spending your money? If you really stop to track it down,
                you would get surprised! Proper budget management depends on real data... and this
                app will help you with that!
            </p>
        </pb-article>

        <pb-article>
            <h1>Alerts</h1>
            <p>
                What if your clothing budget ended? You will get an alert. The goal is to never go over the budget.
            </p>
        </pb-article>

        <pb-article>
            <h1>Results</h1>
            <p>
                People who stick to a financial plan, budgeting every expense, get out of debt faster!
                Also, they to live happier lives... since they expend without guilt or fear...
                because they know it is all good and accounted for.
            </p>
        </pb-article>

        <article>
            <h1>Chart</h1>
            <p>
                <canvas id="myChart" width="400" height="400"></canvas>
            </p>
        </article>

    </div>

</main>
